# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: zunceng's blog
email: zunceng@gmail.com
description: 会点c++ lua nodejs 每天踩狗屎的人
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fruneng.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
weibo_username: chucheng1988
github_username:  fruneng

friends: 
    - name: Google
      link: http://google.com
    - name: 现役
      link: http://www.zenzet.com/
    - name: Place for rent
      link: http://fruneng.github.io/#